name = "qa-bookstore-3"
type = "webpack"
account_id = "b3dad22670b88424da9afddc967218a2"
workers_dev = true
route = ""
zone_id = ""
vars = { DC_LIST="qa1-sfo2", C8_URL="https://qa1-sfo2.eng3.macrometa.io", C8_API_KEY="cloudflare_macrometa.io.bookstore.yP2HmNqf1jZwGpqw2jsXcHQjlQg8UdpXOWhBjFN47aRdimJN56G7tf8hINXiTC7uac0daa" }
kv-namespaces = [
    { binding = "BOOK_IMAGES", id = "1fcd1c0a7aae4c958bde0606dd090d95" }
]
[site]
bucket = "./build"
entry-point = "workers-site"
